version: 1
services:
  - type: static_site
    name: decord
    env: static
    buildCommand: cd client && npm install && CI=false npm run build
    staticPublishPath: ./client/build
    routes:
      - type: rewrite
        src: /*
        dest: /index.html
        status: 200
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache