static_sites:
  - name: decord
    buildCommand: cd client && npm install && npm run build
    publishDirectory: client/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        status: 200
